binop_separator = "Back"
comment_width = 100
condense_wildcard_suffixes = true
error_on_line_overflow = false
format_strings = true
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
wrap_comments = true
